export const Colors = {
    light: {
        titleText: '#2A2A2A',
        background: '#f8f8f8',
        backgroundLogin: '#ffffff',
        button: '#588157',
        buttonText: '#ffffff',
        secondaryButtonOutline: '#2a2a2a',
        primary: '#496348',
        tableHeaderText: '#ffffff',
        searchHint: '#949494',
        borderWidget: '#B0B0B0',
        text: '#454545',
        tabActiveBackground: '#A7C1A7',
        tabTint: '#2e2e2e',
        expandableButtonBackground: '#f6f6f6',
        expandableDetailLabel: '#737373',
        expandableDetailValue: '#454545',
        expandableQuantityButtonBorder: '#CACACA',
        cancelColor: '#B04A3C',
        tableBorder: '#f0f0f0',
    },
    dark: {
        titleText: '#E0E0E0',
        background: '#1E1E1E',
        backgroundLogin: '#2C2C2C',
        button: '#588157',
        buttonText: '#FFFFFF',
        secondaryButtonOutline: '#E0E0E0',
        primary: '#496348',
        tableHeaderText: '#ffffff',
        searchHint: '#A0A0A0',
        borderWidget: '#262626',
        text: '#C5C5C5',
        tabActiveBackground: '#385238',
        tabTint: '#E0E0E0',
        expandableButtonBackground: '#1E1E1E',
        expandableDetailLabel: '#AAAAAA',
        expandableDetailValue: '#D0D0D0',
        expandableQuantityButtonBorder: '#555555',
        cancelColor: '#CF6679',
        tableBorder: '#262626',
    }
};

export type ThemeColors = typeof Colors.light;
